// Code generated by options-gen v0.55.3. DO NOT EDIT.

package runtime

import (
	fmt461e464ebed9 "fmt"
	"time"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
	"github.com/tgbotkit/client"
	"github.com/tgbotkit/runtime/eventemitter"
	"github.com/tgbotkit/runtime/logger"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	botToken string,
	options ...OptOptionsSetter,
) Options {
	var o Options

	// Setting defaults from field tag (if present)

	o.startupTimeout, _ = time.ParseDuration("10s")
	o.defaultMiddlewareEnabled = true
	o.defaultListenersEnabled = true

	o.botToken = botToken

	for _, opt := range options {
		opt(&o)
	}
	return o
}

// botUsername is the bot username used for command mention filtering.
func WithBotUsername(opt string) OptOptionsSetter {
	return func(o *Options) { o.botUsername = opt }
}

// client is the Telegram API client.
func WithClient(opt client.ClientWithResponsesInterface) OptOptionsSetter {
	return func(o *Options) { o.client = opt }
}

// eventEmitter is the event emitter to use.
func WithEventEmitter(opt eventemitter.EventEmitter) OptOptionsSetter {
	return func(o *Options) { o.eventEmitter = opt }
}

// updateSource is the update source to use.
func WithUpdateSource(opt UpdateSource) OptOptionsSetter {
	return func(o *Options) { o.updateSource = opt }
}

// logger is the logger to use.
func WithLogger(opt logger.Logger) OptOptionsSetter {
	return func(o *Options) { o.logger = opt }
}

// startupTimeout bounds blocking startup API calls.
func WithStartupTimeout(opt time.Duration) OptOptionsSetter {
	return func(o *Options) { o.startupTimeout = opt }
}

// defaultMiddlewareEnabled controls registration of runtime middleware.
func WithDefaultMiddlewareEnabled(opt bool) OptOptionsSetter {
	return func(o *Options) { o.defaultMiddlewareEnabled = opt }
}

// defaultListenersEnabled controls registration of runtime listeners.
func WithDefaultListenersEnabled(opt bool) OptOptionsSetter {
	return func(o *Options) { o.defaultListenersEnabled = opt }
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("startupTimeout", _validate_Options_startupTimeout(o)))
	return errs.AsError()
}

func _validate_Options_startupTimeout(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.startupTimeout, "gt=0"); err != nil {
		return fmt461e464ebed9.Errorf("field `startupTimeout` did not pass the test: %w", err)
	}
	return nil
}
