version: '3'

tasks:
  lint:
    desc: Run linters
    cmds:
      - go tool golangci-lint run ./...

  test:
    desc: Run tests
    cmds:
      - go test -race -v -timeout 1m ./...

  generate:
    desc: Run code generation
    cmds:
      - go generate ./...

  coverage:
    desc: Calculate code coverage
    cmds:
      - go test -timeout 1m -coverprofile=coverage.out ./...
      - go tool cover -func=coverage.out

