// Package messagetype provides constants and utilities for identifying the type of a Telegram message.
package messagetype

// MessageType used for message routing.
type MessageType string

// Constants for message types, derived from the client.Message struct.
const (
	// Standard content message types.
	Text      MessageType = "text"
	Animation MessageType = "animation"
	Audio     MessageType = "audio"
	Document  MessageType = "document"
	Photo     MessageType = "photo"
	Sticker   MessageType = "sticker"
	Story     MessageType = "story"
	Video     MessageType = "video"
	VideoNote MessageType = "video_note"
	Voice     MessageType = "voice"
	Contact   MessageType = "contact"
	Dice      MessageType = "dice"
	Game      MessageType = "game"
	Poll      MessageType = "poll"
	Venue     MessageType = "venue"
	Location  MessageType = "location"
	Invoice   MessageType = "invoice"
	Checklist MessageType = "checklist"
	PaidMedia MessageType = "paid_media"
	Giveaway  MessageType = "giveaway"

	// Service message types.
	BoostAdded                   MessageType = "boost_added"
	ChatBackgroundSet            MessageType = "chat_background_set"
	ChatShared                   MessageType = "chat_shared"
	ChecklistTasksAdded          MessageType = "checklist_tasks_added"
	ChecklistTasksDone           MessageType = "checklist_tasks_done"
	ConnectedWebsite             MessageType = "connected_website"
	DeleteChatPhoto              MessageType = "delete_chat_photo"
	DirectMessagePriceChanged    MessageType = "direct_message_price_changed"
	ForumTopicClosed             MessageType = "forum_topic_closed"
	ForumTopicCreated            MessageType = "forum_topic_created"
	ForumTopicEdited             MessageType = "forum_topic_edited"
	ForumTopicReopened           MessageType = "forum_topic_reopened"
	GeneralForumTopicHidden      MessageType = "general_forum_topic_hidden"
	GeneralForumTopicUnhidden    MessageType = "general_forum_topic_unhidden"
	Gift                         MessageType = "gift"
	GiftUpgradeSent              MessageType = "gift_upgrade_sent"
	GiveawayCompleted            MessageType = "giveaway_completed"
	GiveawayCreated              MessageType = "giveaway_created"
	GiveawayWinners              MessageType = "giveaway_winners"
	GroupChatCreated             MessageType = "group_chat_created"
	LeftChatMember               MessageType = "left_chat_member"
	MessageAutoDeleteTimerChanged  MessageType = "message_auto_delete_timer_changed"
	MigrateFromChatID            MessageType = "migrate_from_chat_id"
	MigrateToChatID              MessageType = "migrate_to_chat_id"
	NewChatMembers               MessageType = "new_chat_members"
	NewChatPhoto                 MessageType = "new_chat_photo"
	NewChatTitle                 MessageType = "new_chat_title"
	PaidMessagePriceChanged      MessageType = "paid_message_price_changed"
	PassportData                 MessageType = "passport_data"
	PinnedMessage                MessageType = "pinned_message"
	ProximityAlertTriggered      MessageType = "proximity_alert_triggered"
	RefundedPayment              MessageType = "refunded_payment"
	SuccessfulPayment            MessageType = "successful_payment"
	SuggestedPostApprovalFailed  MessageType = "suggested_post_approval_failed"
	SuggestedPostApproved        MessageType = "suggested_post_approved"
	SuggestedPostDeclined        MessageType = "suggested_post_declined"
	SuggestedPostPaid            MessageType = "suggested_post_paid"
	SuggestedPostRefunded        MessageType = "suggested_post_refunded"
	SupergroupChatCreated        MessageType = "supergroup_chat_created"
	ChannelChatCreated           MessageType = "channel_chat_created"
	UniqueGift                   MessageType = "unique_gift"
	UsersShared                  MessageType = "users_shared"
	VideoChatEnded               MessageType = "video_chat_ended"
	VideoChatParticipantsInvited MessageType = "video_chat_participants_invited"
	VideoChatScheduled           MessageType = "video_chat_scheduled"
	VideoChatStarted             MessageType = "video_chat_started"
	WebAppData                   MessageType = "web_app_data"
	WriteAccessAllowed           MessageType = "write_access_allowed"

	// Unknown message type.
	Unknown MessageType = "unknown"
)