// Code generated by options-gen v0.55.3. DO NOT EDIT.

package updatepoller

import (
	fmt461e464ebed9 "fmt"
	"time"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
	"github.com/tgbotkit/client"
	"github.com/tgbotkit/runtime/logger"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	client client.ClientWithResponsesInterface,
	options ...OptOptionsSetter,
) Options {
	var o Options

	// Setting defaults from field tag (if present)

	o.pollingInterval, _ = time.ParseDuration("1s")

	o.client = client

	for _, opt := range options {
		opt(&o)
	}
	return o
}

// pollingInterval is the interval between polling requests.
func WithPollingInterval(opt time.Duration) OptOptionsSetter {
	return func(o *Options) { o.pollingInterval = opt }
}

// offsetStore is the store to use for storing the update offset.
func WithOffsetStore(opt OffsetStore) OptOptionsSetter {
	return func(o *Options) { o.offsetStore = opt }
}

// logger is the logger to use.
func WithLogger(opt logger.Logger) OptOptionsSetter {
	return func(o *Options) { o.logger = opt }
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("client", _validate_Options_client(o)))
	errs.Add(errors461e464ebed9.NewValidationError("offsetStore", _validate_Options_offsetStore(o)))
	return errs.AsError()
}

func _validate_Options_client(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.client, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `client` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_offsetStore(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.offsetStore, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `offsetStore` did not pass the test: %w", err)
	}
	return nil
}
