// Code generated by options-gen v0.55.3. DO NOT EDIT.

package eventemitter

type OptOptionsSetter func(o *Options)

func NewOptions(
	options ...OptOptionsSetter,
) Options {
	var o Options

	// Setting defaults from field tag (if present)

	o.stopOnError = true

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithErrorHandler(opt ErrorHandler) OptOptionsSetter {
	return func(o *Options) { o.errorHandler = opt }
}

func WithStopOnError(opt bool) OptOptionsSetter {
	return func(o *Options) { o.stopOnError = opt }
}

func (o *Options) Validate() error {
	return nil
}
